# Skapa ett workflow som triggar manuellt och:

# 1. Printa ut slogan

name: secret stuff 
on: 
  workflow_dispatch:
    inputs: 
      num:
        type: string
        description: "select number to guess"
        default: "3"
        
jobs:
  print-slogan:   
    runs-on: ubuntu-latest
    env:
      SLOGAN: ${{vars.SLOGAN}}
    steps:
      - run: echo ${{vars.SLOGAN}}
      - run: echo $SLOGAN

# 2. Guess mangic number
  guess-magic-number:
    runs-on: unbuto-latest
    env:
      MY_MAGIC_NUMBER: ${{secrets.MY_MAGIC_NUMBER}}
    steps:
      - name: Guess Magic Number
        run: echo ${{secrets.MY_MAGIC_NUMBER}}
        
      - name: Print Magic Number 2
        run: echo $MY_MAGIC_NUMBER

      - name: Print Magic Number
        if: always()
        run: |
          if ["${{secrets.MY_MAGIC_NUMBER}}" = ${{inputs.num}}"]; then
            echo "Yay the magic number was:" ${{inputs.num}}"];
          fi  
        

