# Skapa ett workflow som triggar manuellt och:

# 1. Printar ut slogan

name: secret stuff 
on: 
  workflow_dispatch:
    inputs: 
      num:
        type: string
        description: "select number to guess"
        default: "3"
        
jobs:
  print-slogan:   
    runs-on: ubuntu-latest
    env:
      SLOGAN: ${{vars.SLOGAN}}
    steps:
      - run: echo ${{vars.SLOGAN}}
      - run: echo $SLOGAN

# 2. Gissar MY_MAGIC_NUMBER

  guess-magic-number:
    runs-on: unbuto-latest
    env:
      MY_MAGIC_NUMBER: ${{secrets.MY_MAGIC_NUMBER}}
    steps:
    
      - name: Print Magic Number
        run: echo $MY_MAGIC_NUMBER

      - name: Print Magic Number With environment variable 
        run: |          
          new_value=$((MY_MAGIC_NUMBER + 1))         
          echo $new_value
    
      - name: Guess Magic Number
        run: echo ${{secrets.MY_MAGIC_NUMBER}}
      
      - name: Guess Magic Number with secrets context
        if: always()
        run: |
          if ["${{ secrets.MY_MAGIC_NUMBER }}" = "${{ inputs.num }}"]; then
            echo "Yay! The magic number was:  ${{ inputs.num }}"
          fi  
          
      - name: Guess Magic Number with environment var
        if: always()
        run: |
          if ["${{secrets.MY_MAGIC_NUMBER}}" = ${{inputs.num}}"]; then
            echo "Yay the magic number was:" ${{inputs.num}}"];
          fi  
        

