name: Testing to print
on: 
  workflow_dispatch:
   inputs:
       word:
       description: "Print word"
       required: true
       type: string

jobs:
  print-word:
  runs-on: ubuntu-latset

  steps:
    - name: Print word
      run: eco "${{github.event.inputs.word}}"
      
 
